// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "../contracts/PhantomX_Production_Executor.sol";

interface VmInvocation { function addr(uint256 privateKey) external returns(address); function sign(uint256 privateKey,bytes32 digest) external returns(uint8 v,bytes32 r,bytes32 s); function expectRevert() external; }
interface IExecutorInvocationTarget { function executeOpportunity(PhantomX_Production_Executor.ExecutionIntent memory intent) external; }
interface IExecutorCallbackInvocationTarget { function executeOperation(address asset,uint256 amount,uint256 premium,address initiator,bytes calldata params) external returns(bool); }
contract SilentAaveProviderInvocation is IPool { function flashLoanSimple(address,address,uint256,bytes calldata,uint16) external override {} }
contract SilentBalancerProviderInvocation is IBalancerVault { function flashLoan(address,address[] memory,uint256[] memory,bytes memory) external override {} }
contract SilentUniswapV3ProviderInvocation is IUniswapV3Pool { address public token0Address; address public token1Address; constructor(address a,address b){token0Address=a;token1Address=b;} function token0() external view override returns(address){return token0Address;} function token1() external view override returns(address){return token1Address;} function flash(address,uint256,uint256,bytes calldata) external override {} }
contract MockInvocationERC20 is IERC20 { mapping(address=>uint256) internal balances; mapping(address=>mapping(address=>uint256)) internal allowances; function balanceOf(address account) external view override returns(uint256){return balances[account];} function transfer(address recipient,uint256 amount) external override returns(bool){require(balances[msg.sender]>=amount,"balance"); balances[msg.sender]-=amount; balances[recipient]+=amount; return true;} function approve(address spender,uint256 amount) external override returns(bool){allowances[msg.sender][spender]=amount; return true;} function mint(address recipient,uint256 amount) external { balances[recipient]+=amount; } }
contract MockInvocationV2Router is IUniswapV2Router { function swapExactTokensForTokens(uint amountIn,uint,address[] calldata,address,uint) external pure override returns(uint[] memory amounts){amounts=new uint[](2); amounts[0]=amountIn; amounts[1]=amountIn;} }
contract ReentrantAaveProviderInvocation is IPool { address public executor; bool public attempted; bool public rejected; bytes32 public nestedRevertHash; constructor(address e){executor=e;} function flashLoanSimple(address receiverAddress,address asset,uint256 amount,bytes calldata params,uint16) external override { attempted=true; PhantomX_Production_Executor.ExecutionIntent memory nested; (bool ok,bytes memory data)=executor.call(abi.encodeCall(IExecutorInvocationTarget.executeOpportunity,(nested))); rejected=!ok; nestedRevertHash=keccak256(data); MockInvocationERC20(asset).mint(receiverAddress,amount); require(IExecutorCallbackInvocationTarget(receiverAddress).executeOperation(asset,amount,0,receiverAddress,params),"callback failed"); } }
contract PhantomXExecutorCallbackInvocationHarness is PhantomX_Production_Executor { constructor(address signer){owner=signer;} function allowAave(address p) external {isAavePool[p]=true;} function allowBalancer(address p) external {isBalancerVault[p]=true;} function allowUniswapV3(address p) external {isUniswapV3Pool[p]=true;} function allowRouter(address r) external {allowedRouters[r]=true;} function allowToken(address t) external {allowedTokens[t]=true;} }
contract PhantomXExecutorCallbackInvocationTest {
 VmInvocation internal constant vm=VmInvocation(address(uint160(uint256(keccak256("hevm cheat code"))))); uint256 internal constant PRIVATE_KEY=0x0123456789012345678901234567890123456789012345678901234567890123; address internal signer; PhantomXExecutorCallbackInvocationHarness internal executor;
 function setUp() public {signer=vm.addr(PRIVATE_KEY);executor=new PhantomXExecutorCallbackInvocationHarness(signer);}
 function _structHash(PhantomX_Production_Executor.ExecutionIntent memory intent) internal pure returns(bytes32){bytes32 typeHash=keccak256("ExecutionIntent(bytes32 executionId,uint8 providerType,address providerAddress,address tokenBorrow,uint256 amountBorrow,uint8 swap1Type,address routerA,bytes pathA,uint256 minAmountOut1,uint8 swap2Type,address routerB,bytes pathB,uint256 minAmountOutFinal,uint256 minimumOnChainSurplus,uint256 maximumGasLimit,uint256 deadline)");bytes32[17] memory w;w[0]=typeHash;w[1]=intent.executionId;w[2]=bytes32(uint256(uint8(intent.providerType)));w[3]=bytes32(uint256(uint160(intent.providerAddress)));w[4]=bytes32(uint256(uint160(intent.tokenBorrow)));w[5]=bytes32(intent.amountBorrow);w[6]=bytes32(uint256(uint8(intent.swap1Type)));w[7]=bytes32(uint256(uint160(intent.routerA)));w[8]=keccak256(intent.pathA);w[9]=bytes32(intent.minAmountOut1);w[10]=bytes32(uint256(uint8(intent.swap2Type)));w[11]=bytes32(uint256(uint160(intent.routerB)));w[12]=keccak256(intent.pathB);w[13]=bytes32(intent.minAmountOutFinal);w[14]=bytes32(intent.minimumOnChainSurplus);w[15]=bytes32(intent.maximumGasLimit);w[16]=bytes32(intent.deadline);return keccak256(abi.encodePacked(w));}
 function _digest(PhantomX_Production_Executor.ExecutionIntent memory intent) internal view returns(bytes32){return keccak256(abi.encodePacked(bytes2(0x1901),executor.DOMAIN_SEPARATOR(),_structHash(intent)));}
 function _signed(PhantomX_Production_Executor.ExecutionIntent memory intent) internal returns(PhantomX_Production_Executor.ExecutionIntent memory){(uint8 v,bytes32 r,bytes32 s)=vm.sign(PRIVATE_KEY,_digest(intent));intent.signature=abi.encodePacked(r,s,v);return intent;}
 function _intent(PhantomX_Production_Executor.FlashProviderType t,address p) internal pure returns(PhantomX_Production_Executor.ExecutionIntent memory i){i.executionId=keccak256(abi.encode("callback-invocation",p));i.providerType=t;i.providerAddress=p;i.tokenBorrow=address(0x3333333333333333333333333333333333333333);i.amountBorrow=123456789;i.swap1Type=PhantomX_Production_Executor.SwapType.V2;i.routerA=address(0x4444444444444444444444444444444444444444);i.pathA=hex"1234";i.minAmountOut1=120000000;i.swap2Type=PhantomX_Production_Executor.SwapType.V2;i.routerB=address(0x5555555555555555555555555555555555555555);i.pathB=hex"1234";i.minAmountOutFinal=125000000;i.minimumOnChainSurplus=500000;i.maximumGasLimit=5000000;i.deadline=2000000000;}
 function _executableAaveIntent(address provider,address token,address routerA,address routerB) internal pure returns(PhantomX_Production_Executor.ExecutionIntent memory i){address[] memory pathA=new address[](2); pathA[0]=token; pathA[1]=address(0x7777777777777777777777777777777777777777); address[] memory pathB=new address[](2); pathB[0]=pathA[1]; pathB[1]=token; i.executionId=keccak256(abi.encode("callback-invocation-reentry",provider)); i.providerType=PhantomX_Production_Executor.FlashProviderType.AAVE; i.providerAddress=provider; i.tokenBorrow=token; i.amountBorrow=123456789; i.swap1Type=PhantomX_Production_Executor.SwapType.V2; i.routerA=routerA; i.pathA=abi.encode(pathA); i.minAmountOut1=i.amountBorrow; i.swap2Type=PhantomX_Production_Executor.SwapType.V2; i.routerB=routerB; i.pathB=abi.encode(pathB); i.minAmountOutFinal=i.amountBorrow; i.minimumOnChainSurplus=0; i.maximumGasLimit=5000000; i.deadline=2000000000; }
 function test_aave_provider_must_invoke_callback_and_revert_clears_state() public {SilentAaveProviderInvocation p=new SilentAaveProviderInvocation();executor.allowAave(address(p));PhantomX_Production_Executor.ExecutionIntent memory i=_signed(_intent(PhantomX_Production_Executor.FlashProviderType.AAVE,address(p)));vm.expectRevert();executor.executeOpportunity(i);require(executor.activeExecutionId()==bytes32(0),"active execution leaked");}
 function test_balancer_provider_must_invoke_callback_and_revert_clears_state() public {SilentBalancerProviderInvocation p=new SilentBalancerProviderInvocation();executor.allowBalancer(address(p));PhantomX_Production_Executor.ExecutionIntent memory i=_signed(_intent(PhantomX_Production_Executor.FlashProviderType.BALANCER,address(p)));vm.expectRevert();executor.executeOpportunity(i);require(executor.activeExecutionId()==bytes32(0),"active execution leaked");}
 function test_uniswap_v3_provider_must_invoke_callback_and_revert_clears_state() public {SilentUniswapV3ProviderInvocation p=new SilentUniswapV3ProviderInvocation(address(0x3333333333333333333333333333333333333333),address(0x6666666666666666666666666666666666666666));executor.allowUniswapV3(address(p));PhantomX_Production_Executor.ExecutionIntent memory i=_signed(_intent(PhantomX_Production_Executor.FlashProviderType.UNISWAP_V3,address(p)));vm.expectRevert();executor.executeOpportunity(i);require(executor.activeExecutionId()==bytes32(0),"active execution leaked");}
 function test_aave_provider_reentrant_executeOpportunity_is_rejected() public {MockInvocationERC20 token=new MockInvocationERC20(); MockInvocationV2Router routerA=new MockInvocationV2Router(); MockInvocationV2Router routerB=new MockInvocationV2Router(); ReentrantAaveProviderInvocation p=new ReentrantAaveProviderInvocation(address(executor)); executor.allowAave(address(p)); executor.allowToken(address(token)); executor.allowToken(address(0x7777777777777777777777777777777777777777)); executor.allowRouter(address(routerA)); executor.allowRouter(address(routerB)); PhantomX_Production_Executor.ExecutionIntent memory i=_signed(_executableAaveIntent(address(p),address(token),address(routerA),address(routerB))); executor.executeOpportunity(i); require(p.attempted(),"reentry was not attempted"); require(p.rejected(),"reentry was not rejected"); require(p.nestedRevertHash()==keccak256(abi.encodeWithSignature("Error(string)","ReentrancyGuard")),"unexpected reentry revert"); require(executor.activeExecutionId()==bytes32(0),"active execution leaked after reentry");}
}
